// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldiooykwootoeigapfkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaW9veWt3b290b2VpZ2FwZmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjAxMTcsImV4cCI6MjA2Nzk5NjExN30.pWgSPbAMJIY-N0qlVdXBdWRFYBMrUI67Vr-533BgD8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});